//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUDReact.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public decimal ID { get; set; }
        public decimal CustomerId { get; set; }
        public decimal ProductId { get; set; }
        public decimal StoreId { get; set; }
        public System.DateTime DateSold { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Product Product { get; set; }
        public virtual Store Store { get; set; }
    }
}
